name: ServerLink
version: 1.0.3
main: com.serverlink.Main
api-version: 26.1
authors: []
description: Paper26.x Java25 Vanilla Transfer No Proxy v1.0.3
commands:
  serverlink:
    description: ServerLink main command
    permission: serverlink.use
  server:
    description: Quick transfer command
permissions:
  serverlink.use:
    default: true
  serverlink.reload:
    default: op
  serverlink.transfer:
    default: true
  serverlink.optransfer:
    default: op
  serverlink.server:
    default: op